name: Health Check

on:
  # push:
  #   branches:
  #     master
  schedule:
    - cron: '00 20 * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: jtalk/url-health-check-action@v3
        with:
          url: https://throbbing-wood-6405.fly.dev/
