name: Deployment pipeline

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Check style
        run: pnpm run eslint
      - run: pnpm run build
      - run: pnpm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: pnpm run test:e2e
          start: pnpm run start-prod
          wait-on: http://localhost:5000
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
